apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: database
  labels:
    app: postgres
    tier: database
    app.kubernetes.io/part-of: k8s-tuto
  annotations:
    description: "Pod PostgreSQL - module 02 (pod nu, sans Deployment)"
spec:
  containers:
    - name: postgres
      image: postgres:16-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: "usersdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "changeme"  # En clair pour ce module uniquement — corrigé au module 04
