apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: api
  labels:
    app: api
    app.kubernetes.io/part-of: k8s-tuto
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASSWORD: "S3cur3P@ssw0rd!"
