apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: api
  labels:
    app: api
    app.kubernetes.io/part-of: k8s-tuto
data:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "usersdb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
    app.kubernetes.io/part-of: k8s-tuto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: api
          image: simonjaricot/k8s-tuto-api:v1.0.3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
