apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/part-of: k8s-tuto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: api
  labels:
    app: api
    app.kubernetes.io/part-of: k8s-tuto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
    app.kubernetes.io/part-of: k8s-tuto
